name: Auto Sync with Upstream and Build

on:
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/wntrtech/lx-ui.git || true
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories -m "Auto-merge from upstream"

      - name: Set up Node.js and pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.7.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies (try frozen first)
        run: |
          pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Commit and push built files, lockfile, and changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist -f || true
          git add pnpm-lock.yaml || true
          git commit -m "chore: auto-sync, build output, update lockfile" || echo "No changes"
          git push origin main
